spring:
  application:
      name: profeco-service
  config:
      import: "optional:configserver:http://localhost:8088"
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/bd_profeco
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
spring-jpa:
  properties:
    hibernate:
      format_sql: 'true'
      

