
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: supermercado-service
          uri: lb://supermercado-service
          predicates:
            - Path=/supermercado/**
            
        - id: consumidor-service
          uri: lb://consumidor-service
          predicates:
            - Path=/consumidor/**